server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    # content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
#    mode: HTML5
#    prefix: /templates/
#    suffix: .html
    # template-resolver-order:
    # view-names:





  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true


logging:
  file: logs/application.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ROOT: DEBUG
    org.thymeleaf: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.h2.server.web: DEBUG
